; 第12题：键盘输入下列两组十进制数，求其和，并将结果显示在屏幕上：
; 35789418和46531425
; Coded by: Mosles Signall
; Date: 2025-Oct-27

DATAS SEGMENT
    NUMBER1 DB 8 DUP(0)
    NUMBER2 DB 8 DUP(0)
    RESULT DB 8 DUP(0)
DATAS ENDS

STACKS SEGMENT
    DW 100 DUP(?)
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX

INPUT1:
    MOV CX,8
    MOV SI,0
    MOV AH,1

INPUT1_LOOP:
    INT 21H
    SUB AL,30H
    MOV NUMBER1[SI],AL
    INC SI
    LOOP INPUT1_LOOP

INPUT2:
    MOV AH,2
    MOV DX,0AH
    INT 21H
    MOV CX,8
    MOV SI,0
    MOV AH,1

INPUT2_LOOP:
    INT 21H
    MOV NUMBER2[SI],AL
    INC SI
    LOOP INPUT2_LOOP

ADDITION:
    MOV AH,2
    MOV DX,0AH
    INT 21H
    MOV SI,7
    MOV CX,8

ADDITION_LOOP:
    MOV AL,NUMBER1[SI]
    ADD AL,NUMBER2[SI]
    CMP AL,39H
    JA PLUS1
    PLUS1_END:
    MOV RESULT[SI],AL
    DEC SI
    LOOP ADDITION_LOOP

DISPLAY:
    MOV CX,8
    MOV SI,0
    MOV AH,2

DISPLAY_LOOP:
    MOV DL,RESULT[SI]
    INT 21H
    INC SI
    LOOP DISPLAY_LOOP

EXIT:
    MOV AH,4CH
    INT 21H 

PLUS1:
    ADD NUMBER2[SI-1],1
    SUB AL,10D
    JMP PLUS1_END

CODES ENDS
    END START