; 第13题：键盘输入一串二进制数1ah,7ch,0bah,3ah,45h,63h求其和，并将结果显示在屏幕上
; Coded by: Mosles Signall
; Date: 2025-Oct-28

DATAS SEGMENT
    NUMBER DB 8 DUP(0)
    RESULT DB 16 DUP(30H)
DATAS ENDS

STACKS SEGMENT
    DW 100 DUP(?)
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    MOV CX,6

INPUT:
    PUSH CX
    MOV CX,8
    MOV SI,0
    MOV AH,1

INPUT_LOOP:
    INT 21H
    SUB AL,30H
    MOV NUMBER[SI],AL
    INC SI
    LOOP INPUT_LOOP

ADDITION:
    MOV AH,2
    MOV DX,10
    INT 21H
    MOV CX,16
    MOV SI,15
    
ADDITION_LOOP:
    CMP CX,8
    JA WITH_NUMBER
    JMP WITHOUT_NUMBER
    BACK_ADDITION_LOOP:
    LOOP ADDITION_LOOP

REINITIAL:
    POP CX
    LOOP INPUT

DISPLAY:
    MOV CX,16
    MOV SI,0
    MOV AH,2

DISPLAY_LOOP:
    MOV DL,RESULT[SI]
    INT 21H
    INC SI
    LOOP DISPLAY_LOOP

EXIT:
    MOV AH,4CH
    INT 21H

WITH_NUMBER:
    MOV AL,NUMBER[SI-8]
    ADD AL,RESULT[SI]
    CMP AL,31H
    JA ADD01
    ADD01_END:
    MOV RESULT[SI],AL
    DEC SI
    JMP BACK_ADDITION_LOOP

WITHOUT_NUMBER:
    MOV AL,RESULT[SI]
    CMP AL,31H
    JA ADD01
    JMP ADD01_END
    MOV RESULT[SI],AL
    DEC SI
    JMP BACK_ADDITION_LOOP

ADD01:
    SUB AL,2
    MOV DL,RESULT[SI-1]
    INC DL
    MOV RESULT[SI-1],DL
    JMP ADD01_END

CODES ENDS
    END START